game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.home, name='home'),
    path('user-home/', views.user_home, name='user_home'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('play/', views.play, name='play'),
    path('submission-result/<int:attempted_question_pk>/', views.submission_result, name='submission_result'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('guest-login/', views.guest_login, name='guest_login'),
    path('about/', views.about, name='about'),

]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="lt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Django it!{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/play.css' %}">
    {% block css %}
    {% endblock css %}
</head>
<body class="bg-light d-flex flex-column">

<nav class="navbar navbar-expand-md navbar-dark navbar-custom w-100">
    <div class="container">
        <a class="navbar-brand" href="{% url 'game:home' %}">
            <span class="text-primary fs-3 ms-2 fw-bolder">Django</span><span class="fw-bold text-300 fs-3">it!</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">

            {% if not request.user.is_active %}
                <a href="{% url 'game:leaderboard' %}" class="btn btn-info mt-1 mx-1">Lyderiai</a>
                <a href="{% url 'game:login' %}" class="btn btn-info mt-1"><i class="fa fa-sign-in"
                                                                              aria-hidden="true"></i>
                    Prisijungti</a>
            {% else %}
                <div class="d-flex align-items-center">
                    <h6 class="text-white mb-0 me-3">Sveiki, {{ request.user.username }}</h6>
                    <h6 class="text-white mb-0 me-3"><a href="{% url 'game:leaderboard' %}" class="text-white">Lyderiai</a></h6>
                    <h6 class="mb-0 me-3"><a href="{% url 'game:play' %}" class="text-white">Pažaiskime</a></h6>
                    <a href="{% url 'game:logout' %}" class="btn btn-danger mx-1">Atsijungti <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container-flex container">
    {% block content %}
    {% endblock content %}
</div>

<footer class="custom-footer-bg py-0 w-100">
    <div class="container py-4">
        <ul class="list-inline mb-0 text-center">
            <li class="list-inline-item">&copy; Pažaiskime</li>
                        <li class="list-inline-item"><a href="{% url 'game:about' %}">Apie</a></li>
<br>
            <li class="list-inline-item">Visos teisės saugomos &copy; Django it! 2024.</li>
             <p >
        Platforma veikia naudojant<a class="fw-bold text-primary" href="https://www.djangoproject.com/"
                                     target="_blank"> Django</a>
    </p>

        </ul>
    </div>

</footer>

<!-- jQuery first, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/16.1.3/smooth-scroll.polyfills.min.js"
        integrity="sha384-4O/8AW1y1mOB+Q5nVSIDoYk5m+ZCxdkSF+Lc4OZ4n1z7Z2Zp/6w7B1v4FtxSVdKs"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block js %}
{% endblock js %}
</body>
</html>