game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.home, name='home'),
    path('user-home/', views.user_home, name='user_home'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('play/', views.play, name='play'),
    path('submission-result/<int:attempted_question_pk>/', views.submission_result, name='submission_result'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('guest-login/', views.guest_login, name='guest_login'),
    path('about/', views.about, name='about'),

]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

game/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel


class Question(TimeStampedModel):
    ALLOWED_NUMBER_OF_CORRECT_CHOICES = 1

    html = models.TextField(verbose_name='Klausimas')
    is_published = models.BooleanField(default=False, null=False, verbose_name='Ar paskelbtas')
    maximum_marks = models.DecimalField(default=4, decimal_places=2, max_digits=6, verbose_name='Maksimalūs balai')

    class Meta:
        verbose_name = 'Klausimas'
        verbose_name_plural = 'Klausimai'

    def __str__(self):
        return self.html

class Choice(TimeStampedModel):
    MAX_CHOICES_COUNT = 4

    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE, verbose_name='Klausimas')
    is_correct = models.BooleanField(default=False, null=False, verbose_name='Ar teisingas')
    html = models.TextField(verbose_name='Atsakymas')

    class Meta:
        verbose_name = 'Pasirinkimas'
        verbose_name_plural = 'Pasirinkimai'

    def __str__(self):
        return self.html

class QuizProfile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Vartotojas')
    total_score = models.DecimalField(default=0, decimal_places=2, max_digits=10, verbose_name='Bendras balas')

    class Meta:
        verbose_name = 'Profilis'
        verbose_name_plural = 'Profiliai'

    def __str__(self):
        return f'Vartotojas: {self.user}'

    def get_new_question(self):
        used_questions_pk = AttemptedQuestion.objects.filter(quiz_profile=self).values_list('question__pk', flat=True)
        remaining_questions = Question.objects.exclude(pk__in=used_questions_pk).filter(is_published=True)
        if not remaining_questions.exists():
            return None
        return random.choice(remaining_questions)

    def create_attempt(self, question):
        attempted_question = AttemptedQuestion(question=question, quiz_profile=self)
        attempted_question.save()

    def evaluate_attempt(self, attempted_question, selected_choice):
        if attempted_question.question_id != selected_choice.question_id:
            return

        attempted_question.selected_choice = selected_choice
        if selected_choice.is_correct:
            attempted_question.is_correct = True
            attempted_question.marks_obtained = attempted_question.question.maximum_marks

        attempted_question.save()
        self.update_score()

    def update_score(self):
        marks_sum = self.attempts.filter(is_correct=True).aggregate(
            models.Sum('marks_obtained'))['marks_obtained__sum']
        self.total_score = marks_sum or 0
        self.save()

class AttemptedQuestion(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Klausimas')
    quiz_profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='attempts',
                                     verbose_name='Profilis')
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True, verbose_name='Pasirinkimas')
    is_correct = models.BooleanField(default=False, null=False, verbose_name='Ar teisingas')
    marks_obtained = models.DecimalField(default=0, decimal_places=2, max_digits=6, verbose_name='Gauti balai')

    class Meta:
        verbose_name = 'Bandytas klausimas'
        verbose_name_plural = 'Bandyti klausimai'

    def get_absolute_url(self):
        return f'Rezultatai:{self.pk}'

game/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, get_user_model
from .models import Question, Choice

class GuestUserForm(forms.Form):
    username = forms.CharField(max_length=150, label='Vartotojo vardas', required=True)

# Esamos formos
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['html', 'is_published']
        widgets = {
            'html': forms.Textarea(attrs={'rows': 3, 'cols': 80}),
        }
        labels = {
            'html': 'HTML turinys',
            'is_published': 'Ar paskelbtas'
        }

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['html', 'is_correct']
        widgets = {
            'html': forms.Textarea(attrs={'rows': 2, 'cols': 80}),
        }
        labels = {
            'html': 'HTML turinys',
            'is_correct': 'Ar teisingas'
        }

class ChoiceInlineFormset(forms.BaseInlineFormSet):
    def clean(self):
        super(ChoiceInlineFormset, self).clean()
        correct_choices_count = 0
        for form in self.forms:
            if not form.is_valid():
                return
            if form.cleaned_data and form.cleaned_data.get('is_correct') is True:
                correct_choices_count += 1
        try:
            assert correct_choices_count == Question.ALLOWED_NUMBER_OF_CORRECT_CHOICES
        except AssertionError:
            raise forms.ValidationError('Leidžiamas vienas teisingas pasirinkimas.')

User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField(label='Vartotojo vardas')
    password = forms.CharField(widget=forms.PasswordInput, label='Slaptažodis')

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Tokio vartotojo nėra")
            if not user.check_password(password):
                raise forms.ValidationError("Neteisingas slaptažodis")
            if not user.is_active:
                raise forms.ValidationError("Vartotojas neaktyvus")
        return super(UserLoginForm, self).clean(*args, **kwargs)

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='El. paštas')
    first_name = forms.CharField(required=True, label='Vardas')
    last_name = forms.CharField(required=True, label='Pavardė')

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]
        labels = {
            'username': 'Vartotojo vardas',
            'first_name': 'Vardas',
            'last_name': 'Pavardė',
            'email': 'El. paštas',
            'password1': 'Slaptažodis',
            'password2': 'Pakartokite slaptažodį',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

game/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.contrib.auth.models import User
from .models import QuizProfile, Question, AttemptedQuestion, Choice
from .forms import UserLoginForm, RegistrationForm, GuestUserForm

def home(request):
    context = {}
    return render(request, 'game/home.html', context=context)

@login_required
def user_home(request):
    context = {}
    return render(request, 'game/user_home.html', context=context)

def leaderboard(request):
    top_quiz_profiles = QuizProfile.objects.order_by('-total_score')[:500]
    total_count = top_quiz_profiles.count()
    context = {
        'top_quiz_profiles': top_quiz_profiles,
        'total_count': total_count,
    }
    return render(request, 'game/leaderboard.html', context=context)

@login_required()
def play(request):
    quiz_profile, created = QuizProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        question_pk = request.POST.get('question_pk')
        attempted_question = quiz_profile.attempts.select_related('question').get(question__pk=question_pk)
        choice_pk = request.POST.get('choice_pk')

        try:
            selected_choice = attempted_question.question.choices.get(pk=choice_pk)
        except ObjectDoesNotExist:
            raise Http404

        quiz_profile.evaluate_attempt(attempted_question, selected_choice)
        return redirect('game:submission_result', attempted_question_pk=attempted_question.pk)
    else:
        question = quiz_profile.get_new_question()
        if question is not None:
            quiz_profile.create_attempt(question)

        context = {
            'question': question,
        }
        return render(request, 'game/play.html', context=context)

@login_required()
def submission_result(request, attempted_question_pk):
    attempted_question = get_object_or_404(AttemptedQuestion, pk=attempted_question_pk)
    context = {
        'attempted_question': attempted_question,
    }
    return render(request, 'game/submission_result.html', context=context)

def login_view(request):
    title = "Prisijungti"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('game:user_home')
            else:
                form.add_error(None, "Vartotojas neaktyvus")
        else:
            form.add_error(None, "Neteisingas vartotojo vardas arba slaptažodis")

    # Grąžiname šabloną, jei forma nėra validi arba POST užklausa nepavyko
    return render(request, 'game/login.html', {"form": form, "title": title})



def register(request):
    title = "Sukurti naują paskyrą"
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('game:login')
    else:
        form = RegistrationForm()

    context = {'form': form, 'title': title}
    return render(request, 'game/registration.html', context=context)

def logout_view(request):
    logout(request)
    return redirect('game:home')

def guest_login(request):
    if request.method == 'POST':
        form = GuestUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            guest_user, created = User.objects.get_or_create(username=username)
            if created:
                guest_user.set_unusable_password()
                guest_user.save()
            quiz_profile, created = QuizProfile.objects.get_or_create(user=guest_user)
            login(request, guest_user)
            return redirect('game:play')
    else:
        form = GuestUserForm()
    return render(request, 'game/guest_login.html', {'form': form})

def about(request):
    return render(request, 'game/about.html')

game/templates/game/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1>About Us</h1>
    <p>Welcome to our Django application. Here you can find various quizzes and games to test your knowledge. Our platform is designed to be user-friendly and engaging. Enjoy your time here!</p>
</div>
{% endblock content %}

game/templates/game/guest_login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Įveskite savo vartotojo vardą</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Pradėti žaidimą</button>
    </form>
</div>
{% endblock %}

game/templates/game/home.html
{% extends 'base.html' %}
{% block title %} Žaidimas/Viktorina | Pagrindinis {% endblock title %}
{% block content %}

<section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center bg-light">
    <div class="container text-center">
        <h1 class="display-1 text-info">Pažaiskime</h1>
        <p class="display-4 d-none d-sm-block">Išbandykite savo žinias ir tapkite nugalėtoju.</p>
        <p class="lead">Viktorinos įvairiomis temomis.</p>

        {% if not request.user.is_authenticated %}
            <p class="lead">Prisiregistruokite, jei dar to nepadarėte, ir gaukite prieigą prie daugybės viktorinų jus dominančia tema.</p>
            <p><strong> Pradėkite savo kelionę čia:</strong></p>
            <a href="{% url 'game:register' %}" class="btn btn-lg btn-info mt-1">
                <i class="fa fa-user-plus" aria-hidden="true"></i> Registruotis
            </a>
            <a href="{% url 'game:guest_login' %}" class="btn btn-lg btn-secondary mt-1">
                <i class="fa fa-user" aria-hidden="true"></i> Žaisti kaip svečias
            </a>
        {% else %}
            <a href="{% url 'game:play' %}" class="btn btn-lg btn-success mt-1">
                <i class="fa fa-play-circle" aria-hidden="true"></i> Žaisti
            </a>
            <a href="{% url 'game:leaderboard' %}" class="btn btn-lg btn-warning mt-1">
                <i class="fa fa-trophy" aria-hidden="true"></i> Lyderiai
            </a>
        {% endif %}
    </div>
</section>

{% endblock content %}

game/templates/game/leaderboard.html
{% extends 'base.html' %}
{% block title %} Žaidimas/Viktorina | Lyderiai {% endblock title %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">
        <span class="badge badge-info p-3">
            <i class="fa fa-trophy text-primary" aria-hidden="true"></i> TOP {{ total_count }} žaidėjų <i class="fa fa-trophy text-primary" aria-hidden="true"></i>
        </span>
    </h1>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Vieta</th>
                    <th>Vartotojas</th>
                    <th>Taškai</th>
                </tr>
            </thead>
            <tbody>
                {% for quiz_profile in top_quiz_profiles %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ quiz_profile.user.username }}</td>
                    <td>{{ quiz_profile.total_score }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

game/templates/game/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Žaidimas/ Viktorina | {{ title }} {% endblock title %}
{% block content %}
{% if not request.user.is_active %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Prisijungti</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-info btn-block" value="{{ title }}">
                </form>
              <div class="text-center">
                <p>arba ...</p>
                <a href="{% url 'game:register' %}" class="btn btn-success mb-3">Sukurti paskyrą</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% else %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">Pažaiskime</h1>
        <p class="display-4 d-none d-sm-block">Pasitikrink savo žinias ir tapk nugalėtoju.</p>
        <p class="lead">Viktorinos įvairiomis temomis.</p>
        <a href="{% url 'game:play' %}" class="btn btn-lg btn-info mt-1">Žaisti</a>
        <a href="{% url 'game:leaderboard' %}" class="btn btn-lg btn-info mt-1">Lyderiai</a>
      </div>  
    </section>

{% endif %}

{% endblock content %}

game/templates/game/play.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  {% if question is None %}
  <div class="jumbotron text-center bg-light py-5 rounded">
    <h1>Jūs jau atsakėte į visus mūsų klausimus.</h1>
    <a href="{% url 'game:leaderboard' %}" class="btn btn-lg btn-info mt-4">
      <i class="fa fa-trophy" aria-hidden="true"></i> Žiūrėkite lyderių lentelę čia
      <i class="fa fa-trophy" aria-hidden="true"></i>
    </a>
  </div>
  {% else %}
  <div class="card shadow-sm">
    <div class="card-body">
      <h3 class="card-title text-info">{{ question.html|safe }}</h3>
      <form class="form mt-4" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="question_pk" value="{{ question.pk }}">
        {% for choice in question.choices.all %}
        <div class="form-check my-3">
          <input class="form-check-input" type="radio" name="choice_pk" id="choice-{{ forloop.counter }}" value="{{ choice.pk }}">
          <label class="form-check-label" for="choice-{{ forloop.counter }}">
            {{ choice.html|safe }}
          </label>
        </div>
        {% endfor %}
        <hr>
        <div class="text-center mt-4">
          <input class="btn btn-lg btn-primary" type="submit" value="Pateikti">
        </div>
      </form>
    </div>
  </div>
  {% endif %}
</div>
{% endblock content %}

game/templates/game/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Žaidimas/Viktorina | {{ title }} {% endblock title %}

{% block content %}
{% if not request.user.is_active %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
                <h1 class="mb-3 text-center">Sukurti naują paskyrą</h1>
                <form class="mb-3" method="POST" action="">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-info btn-block mb-3" value="{{ title }}">
                </form>
                <div class="text-center">
                    <p>arba ...</p>
                    <a href="{% url 'game:login' %}" class="btn btn-success">Prisijungti</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}

<section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
    <div class="container text-center">
        <h1 class="display-1 text-info">Pažaiskime</h1>
        <p class="display-4 d-none d-sm-block">Išbandykite savo žinias ir tapkite nugalėtoju.</p>
        <p class="lead">Viktorinos įvairiomis temomis.</p>
        <a href="{% url 'game:play' %}" class="btn btn-lg btn-info mt-1">Žaisti</a>
        <a href="{% url 'game:leaderboard' %}" class="btn btn-lg btn-info mt-1">Lyderiai</a>
    </div>
</section>

{% endif %}
{% endblock content %}

game/templates/game/submission_result.html
{% extends 'base.html' %}
{% block title %}Žaidimas/Viktorina | Rezultatai{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="jumbotron my-4 text-center">
        <h3 class="text-info">{{ attempted_question.question.html|safe }}</h3>

        <p>
            <strong>Jūsų atsakymas: </strong>
            {{ attempted_question.selected_choice.html|safe }}
        </p>

        {% if attempted_question.selected_choice.is_correct %}
        <h4 class="text-success">Puiku! Jūsų atsakymas teisingas. Pirmyn! 🙌</h4>
        {% else %}
        <h4 class="text-danger">Atsakymas neteisingas 😟</h4>
        {% endif %}

        <a class="btn btn-info mt-3" href="{% url 'game:play' %}">Rodyti kitą klausimą</a>
    </div>
</div>
{% endblock content %}

game/templates/game/user_home.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Welcome {% endblock title %}
{% block content %}
<div class="container my-4">
    <div class="jumbotron">

	      <h2 class="text-center text-info">Jūs sėkmingai prisijungėte.</h2>
	      <h3 class="text-info text-center">Prieš žaisdami, susipažinkite su taisyklėmis</h3>

        <div class="row">

            <div class="card border-info mx-4 my-4">
                <div class="card-body text-info">
                    <h4 class="card-title">Taisyklės:</h4>
                    <p class="card-text">
                        <ul style="list-style:decimal;">
                            <li>Visi klausimai yra su keliais atsakymų variantais.</li>
                            <li><span class="text-danger">Tik vienas atsakymas yra teisingas.</span></li>
                            <li>Kiekvienas klausimas turi vienodus balus t.y. <span class="text-danger">4 balai už kiekvieną klausimą.</span>
                            </li>
                            <li>Kiekvienas klausimas rodomas tik vieną kartą.</li>
                            <li>Stenkitės atsakyti kuo greičiau.</li>
                            <li>Jei paspausite atnaujinimą arba grįšite į ankstesnį puslapį, jums bus pateiktas naujas klausimas, o klausimas, kurį klausėte, bus skaičiuojamas kaip bandytas.</li>
                            <li>Klausimai kiekvienam vartotojui rodomi atsitiktine tvarka.</li>
                            <li>Kai tik pateiksite atsakymą, jums bus nedelsiant pranešta, ar jūsų atsakymas buvo teisingas, ar neteisingas.</li>
                        </ul>
                    </p>
                    <a href="{% url 'game:play' %}" class="btn btn-info">Žaisti</a>
                </div>  
                <div class="card-footer">Taisyklės paskutinį kartą keistos 2024</div>
            </div>  
        </div>  

    </div>
</div>
{% endblock content %}